version: "3.9"

services:
  github-runner:
    image: summerwind/actions-runner:latest
    container_name: github-runner
    restart: unless-stopped
    environment:
      RUNNER_REPO: https://github.com/liamj-f/rpi4-docker
      RUNNER_NAME: pi4-runner
      LABELS: self-hosted,docker,pi
      RUNNER_TOKEN: ${GITHUB_TOKEN}   # registration token or PAT
    volumes:
      - ./runner-data:/actions-runner  # persist runner config
