version: "3.9"

services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: github-runner
    restart: no
    environment:
      REPO_URL: https://github.com/liamj-f/rpi4-docker
      RUNNER_NAME: pi4-runner
      RUNNER_WORKDIR: /tmp/github-runner
      RUNNER_GROUP: default
      LABELS: self-hosted,arm64,pi
      ACCESS_TOKEN: ${RUNNER_REG_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-data:/actions-runner

