version: "3.8"

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "84:80"   # Web UI
      - "8443:443"  # HTTPS if you set up TLS
    volumes:
      - nextcloud_data:/var/www/html
      - /mnt/NextCloud:/mnt/NextCLoud
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/status.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_app
      - MYSQL_HOST=mysql
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true

volumes:
  nextcloud_db_data:
    name: nextcloud_db_data
    external: false
  nextcloud_data:
    name: nextcloud_data
    
