version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm_network
volumes:
  nginx_data:
networks:
  npm_network:
    driver: bridge
