version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD:  ${INITIAL_ADMIN_PASSWORD}
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx_network
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
volumes:
  nginx_data:
    name: nginx_data
networks:
  nginx_network:
    driver: bridge
    external: true
