version: '3.8'

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      PASSWORD_ADMIN: ${Admin_Password}
      USERNAME_ADMIN: ${Admin_User}
    extra_hosts:
#      - "nginx.14monarch.local:192.168.0.2:81"
#      - "pihole.14monarch.local:192.168.0.2:82"
#      - "portainer.14monarch.local:192.168.0.2:83"
#      - "nextcloud.14monarch.local:192.168.0.2:84"
       - "tplink.14monarch.local:192.168.0.1:80
    networks:
      - nginx_network
volumes:
  nginx_data:
    name: nginx_data
networks:
  nginx_network:
    driver: bridge
    name: nginx_network
