version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      WEB_PORT: 80
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d

