version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: 'Europe/London'
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_webserver_port: 82
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
    volumes:
      - /data/compose/4/etc-pihole:/etc/pihole
      - /data/compose/4/etc-dnsmasq.d:/etc/dnsmasq.d

volumes:
  pihole_data:
    name: pihole_data
  dnsmasq_data:
    name: dnsmasq_data
