version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: "host"
    environment:
      TZ: 'Europe/London'
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_webserver_port: 82
      DNS1: 1.1.1.1
      DNS2: 8.8.8.8
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
      - ./pihole-custom-dns.conf:/etc/dnsmasq.d/99-custom.conf:ro
volumes:
  pihole_data:
    name: pihole_data
  dnsmasq_data:
    name: dnsmasq_data
