version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "83:9000"  # HTTP UI
      - "9443:9443"  # HTTPS UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - nginx_network  
    healthcheck:
      test:  ["CMD", "/portainer", "--help"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s  
networks:
  nginx_network:
    driver: bridge
    name: nginx_network
volumes:
  portainer_data:
    name: portainer_data
