version: '3.8'

services:
  rathole-client:
    image: ghcr.io/rathole-org/rathole:dev
    container_name: rathole-client
    restart: unless-stopped
    volumes:
      - /opt/stacks/rathole/rathole-client.toml:/app/config.toml
    command: --client /app/config.toml
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true 