services:
  avalon-backend:
    container_name: avalon-backend
    image: ghcr.io/liamj-f/avalon-docker/backend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      PORT: 4000
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      CORS_ORIGIN: "*"

  avalon-ui:
    container_name: avalon-ui
    image: ghcr.io/liamj-f/avalon-docker/frontend:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      BACKEND_HOST: avalon-backend
      BACKEND_PORT: 4000
    ports:
      - "92:80"
    depends_on:
      - avalon-backend
