version: "3.9"

services:
  keepalived:
    image: shawly/keepalived:latest
    container_name: keepalived
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    environment:
      TZ: Europe/London
      KEEPALIVED_CUSTOM_CONFIG: true
    volumes:
      - /opt/stacks/keepalived/keepalived.conf:/etc/keepalived/keepalived.conf:ro
      - /opt/stacks/keepalived/notify.sh:/etc/keepalived/notify.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  pihole:
    depends_on:
      keepalived:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    network_mode: "host"
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "80:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "443:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      - "67:67/udp"
    environment:
      TZ: 'Europe/London'
      FTLCONF_webserver_api_password: ${PIHOLE_WEBPASSWORD}
      FTLCONF_webserver_port: 82
#      FTLCONF_misc_etc_dnsmasq_d: true
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
#      - /home/pi/stacks/pihole/99-pihole-custom.conf:/etc/dnsmasq.d/99-custom.conf

  nginx-proxy-manager:
    depends_on:
      keepalived:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    environment:
      INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD:  ${PIHOLE_WEBPASSWORD}
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "81:81"     # Admin UI
    volumes:
      - nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx_network
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

  nebula-sync:
    depends_on:
      pihole:
    image: ghcr.io/lovelaze/nebula-sync:latest
    depends_on:
      pihole:
        condition: service_healthy
    container_name: nebula-sync
    environment:
      PRIMARY: http://${PRIMARY_IP}:82|${PIHOLE_WEBPASSWORD}
      REPLICAS: http://${SECONDARY_IP}:82|${PIHOLE_WEBPASSWORD}
      FULL_SYNC: false
      SYNC_CONFIG_DNS: true	#Synchronize DNS settings
      SYNC_CONFIG_DNS_EXCLUDE: "interface" #Keep pi0 on wlan0 and wg0
      SYNC_CONFIG_DHCP: true	#Synchronize DHCP settings
      SYNC_CONFIG_DHCP_EXCLUDE: "active" #eclude syncing the active state of the DHCP server to prevent conflicts
      SYNC_CONFIG_NTP: true	#Synchronize NTP settings
      SYNC_CONFIG_RESOLVER: true	#Synchronize resolver settings
      SYNC_CONFIG_DATABASE: true	#Synchronize database settings
      SYNC_CONFIG_MISC: true	#Synchronize miscellaneous settings
      SYNC_CONFIG_DEBUG: true	#Synchronize debug settings
      SYNC_GRAVITY_DHCP_LEASES: true	#Synchronize DHCP leases
      SYNC_GRAVITY_GROUP: true	#Synchronize groups
      SYNC_GRAVITY_AD_LIST: true	#Synchronize ad lists
      SYNC_GRAVITY_AD_LIST_BY_GROUP: true	#Synchronize ad lists by group
      SYNC_GRAVITY_DOMAIN_LIST: true	#Synchronize domain lists
      SYNC_GRAVITY_DOMAIN_LIST_BY_GROUP: true	#Synchronize domain lists by group
      SYNC_GRAVITY_CLIENT: true	#Synchronize clients
      SYNC_GRAVITY_CLIENT_BY_GROUP: true	#Synchronize clients by group
      RUN_GRAVITY: true
      CRON: "*/5 * * * *"
      CLIENT_TIMEOUT_SECONDS: 60
      TZ: "Europe/London"
    restart: unless-stopped

  rsync:
    image: instrumentisto/rsync-ssh
    container_name: rsync
    restart: unless-stopped
    volumes:
      - nginx_data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ~/.ssh:/root/.ssh:ro
    environment:
      - RSYNC_TARGET=${SSH_USER}@${SECONDARY_IP} 
    command: >
      sh -c "while true; do
        rsync -avz --delete
          /data/ ${SSH_USER}@${SECONDARY_IP}:/data/ &&
        rsync -avz --delete
          /etc/letsencrypt/ ${SSH_USER}@${SECONDARY_IP}:/etc/letsencrypt/;
        sleep 300;
      done"

volumes:
  nginx_data:
    name: nginx_data
  pihole_data:
    name: pihole_data
  dnsmasq_data:
    name: dnsmasq_data