version: "3"
services:
  website:
    image: ghcr.io/cyclopsgd/website:latest
    container_name: website
    ports:
        - "91:80"
    environment:
      SITE_TS_FILEPATH: "./website/site.ts"
      ABOUT_TS_FILEPATH: "./website/about.ts"
      EXPERIENCE_TS_FILEPATH: "./website/experience.ts"
      PROJECTS_TS_FILEPATH: "./website/projects.ts"
      SKILLS_TS_FILEPATH: "./website/skills.ts"
      HOMELAB_TS_FILEPATH: "./website/homelab.ts"
      WEBSITE_URL: "liam.james-fagg.uk"
    volumes:
      # Your content files, read-only. The names must match.
      - ./website:/website_files:ro