name: Install Docker on RPI4

on:
  push:
    branches:
      - main
      - '**'
    paths:
      - '.github/workflows/install-docker-RPI4.yml'
  workflow_dispatch:
    inputs:
      host_machine:
        required: true
        type: string 
      domain:
        required: true
        type: string  
  workflow_call:
    inputs:
      host_machine:
        required: true
        type: string 
      domain:
        required: true
        type: string
jobs:
  install_docker:
    runs-on: ubuntu-latest
    env:
      host_machine: ${{ inputs.host_machine || 'rpi4-server' }}
      domain: ${{ inputs.domain || '14monarch.local' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@main 

      - name: Install WireGuard
        run: |
          sudo apt-get install -y wireguard || (sudo apt-get update && sudo apt-get install -y wireguard)  

      - name: Write WireGuard config
        run: |
          cat > wg0.conf << EOF
          [Interface]
          PrivateKey = ${{ secrets.WG_PRIVATE_KEY }}
          Address = 10.5.5.5/32
          DNS = 10.5.5.1
          MTU = 1250

          [Peer]
          PublicKey = ${{ secrets.WG_PUBLIC_KEY }}
          PresharedKey = ${{ secrets.WG_PRESHARED_KEY }}
          AllowedIPs = 192.168.0.0/24, 145.241.244.229/32
          Endpoint = ${{ vars.WG_ENDPOINT }}:51820
          PersistentKeepalive = 25
          EOF

      - name: Override system DNS resolver
        run: |
          sudo rm /etc/resolv.conf
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
          
      - name: Uninstall old Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.RPI4_IP }}
          username: ${{ vars.RPI4_USER }}
          password: ${{ secrets.RPI4_PASSWORD }}
          script: |
            for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do
              sudo apt-get remove -y --allow-change-held-packages $pkg || true
            done
      - name: Add Docker repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.RPI4_IP }}
          username: ${{ vars.RPI4_USER }}
          password: ${{ secrets.RPI4_PASSWORD }}
          script: |
            sudo apt-get update
            sudo apt-get install ca-certificates curl
            sudo install -m 0755 -d /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            
      - name: Install Docker packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.RPI4_IP }}
          username: ${{ vars.RPI4_USER }}
          password: ${{ secrets.RPI4_PASSWORD }}
          script: |
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Configure Docker DNS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.RPI4_IP }}
          username: ${{ vars.RPI4_USER }}
          password: ${{ secrets.RPI4_PASSWORD }}
          script: |
            sudo mkdir -p /etc/docker
            cat <<EOF | sudo tee /etc/docker/daemon.json
            {
              "dns": ["1.1.1.1", "1.0.0.1","${{ vars.KEEPALIVED_IP }}"]
            }
            EOF

            sudo systemctl daemon-reload
            sudo systemctl restart docker
            
      - name: Ensure Docker is running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.RPI4_IP }}
          username: ${{ vars.RPI4_USER }}
          password: ${{ secrets.RPI4_PASSWORD }}
          script: |
            sudo systemctl enable --now docker
            sudo systemctl status docker --no-pager
      - name: Bring down VPN
        run: |
          sudo wg-quick down ./wg0.conf
          sudo wg show   

      - name: add user to docker group
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.RPI4_IP }}
          username: ${{ vars.RPI4_USER }}
          password: ${{ secrets.RPI4_PASSWORD }}
          script: |
            sudo usermod -aG docker ${{ vars.RPI4_USER }}

  deploy_portainer: 
    uses: ./.github/workflows/portainer-deploy.yml
    needs: install_docker
    secrets: inherit
    with:
      host_machine: ${{ inputs.host_machine || 'rpi4-server' }}
      domain: ${{ inputs.domain || '14monarch.local' }}

  deploy_duckdns:
    uses: ./.github/workflows/duckdns-redeploy.yml
    needs: deploy_portainer
    secrets: inherit
    with:
      host_machine: ${{ inputs.host_machine || 'rpi4-server' }}
      domain: ${{ inputs.domain || '14monarch.local' }}
